// Auto-generated by cftranslate from: test.c
// May require manual edits.

#import <standard.fx>;

using standard::io::console;

extern
{
    cdecl scanf(const char *format, ...) -> int;
};

def main() -> int
{
    int rows;
    int i;
    int j;
    print("Enter the number of rows: ");
    scanf("%d", @rows);
    for (i = 1; i <= rows; i++)
    {
        for (j = i; j < rows; j++)
        {
            print(" ");
        };
        for (j = 1; j <= (2 * i - 1); j++)
        {
            print("*");
        };
        print("\n");
    };
    return 0;
};
